version: "3.3"

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ${APP_PATH}:${APP_DOCUMENT_ROOT}
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - izam
    depends_on:
      - php
      - redis
      - db

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ${APP_PATH}:${APP_DOCUMENT_ROOT}
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www/html/devops
    ports:
      - "${VITE_PORT:-5080}:${VITE_PORT:-5080}"
    working_dir: /var/www/html/app
    command: sh /var/www/html/app/start.sh
    networks:
      - izam
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - izam
    volumes:
      - redis_data:/data

  db:
    image: mysql:8.0.32
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-izam-ecommerce}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - izam

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-9090}:80"
    networks:
      - izam

networks:
  izam:
    driver: "bridge"

volumes:
  dbdata:
    driver: local

  redis_data:
    driver: local
